import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { auth, onAuthStateChanged } from "../firebase/firebase.config";

import { login, logout, selectUser } from "@/features/userSlice";
import { Inter } from "next/font/google";
import MainLayout from "../components/layouts/main/mainLayout";
import Banner from "../components/Home/Banner";
import Services from "../components/Home/Services";
import WhatCanDo from "../components/Home/WhatCanDo";
import AnalyzeData from "../components/Home/AnalyzeData";
import Footer from "@/components/Home/Footer";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // =================== REDUX ===================
  const user = useSelector(selectUser);

  // console.log("User: ", user);

  const dispatch = useDispatch();
  // check at page load if a user is authenticated
  useEffect(() => {
    onAuthStateChanged(auth, (userAuth) => {
      if (userAuth) {
        // user is logged in, send the user's details to redux, store the current user in the state
        dispatch(
          login({
            email: userAuth.email,
            uid: userAuth.uid,
            displayName: userAuth.displayName,
            photoUrl: userAuth.photoURL,
          })
        );
      } else {
        dispatch(logout());
      }
    });
  }, []);
  // =================== REDUX ===================
  return (
    <>
      <Head>
        <title>Landlord Hub v2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:heroPattern px-5 sm:px-10 lg:px-0 z-30">
        <div className="servicePattern"></div>
        <div className="lg:container">
          {/* Banner */}
          <Banner />

          {/* Services */}
          <Services />

          {/* What can landlord hub do */}
          <WhatCanDo />

          {/* Analyze section */}
          <AnalyzeData />
        </div>
      </div>
      <Footer />
    </>
  );
}

Home.Layout = MainLayout;
