import Head from "next/head";
import { Inter } from "next/font/google";

import MainLayout from "@/components/layouts/main/mainLayout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Landlord Hub v2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline text-blue-700">
          Hello world! Home page
        </h1>
      </main>
    </>
  );
}

Home.Layout = MainLayout;
